#pragma once
// =============================================================================
// App.h — Base class and type definitions for all PocketOS applications
//
// All apps inherit from App and implement lifecycle callbacks.
// AppManager calls these callbacks; apps must never call each other directly.
// =============================================================================

#include <Arduino.h>
#include <TFT_eSPI.h>

// ---------------------------------------------------------------------------
// Input events — generated by InputManager, dispatched by AppManager
// ---------------------------------------------------------------------------
enum class AppEvent : uint8_t {
    NONE = 0,
    BTN_UP_SHORT,           // UP tapped briefly
    BTN_UP_LONG,            // UP held > BTN_LONG_PRESS_MS
    BTN_UP_HELD,            // Auto-repeat while UP held
    BTN_DOWN_SHORT,
    BTN_DOWN_LONG,
    BTN_DOWN_HELD,
    BTN_SELECT_SHORT,       // SELECT tapped  → confirm / open
    BTN_SELECT_LONG,        // SELECT held    → back  (default system behaviour)
    BTN_SELECT_VERY_LONG,   // SELECT held longer → home (default system)
    BTN_UP_DOWN_COMBO,      // UP + DOWN simultaneously (future use)
};

// ---------------------------------------------------------------------------
// AppInfo — metadata used by Launcher and AppManager
// ---------------------------------------------------------------------------
struct AppInfo {
    uint8_t  id;
    const char* name;
    // Optional icon draw callback: draw a ~20×20 icon centred at (cx, cy)
    void (*drawIcon)(TFT_eSPI& tft, int16_t cx, int16_t cy, uint16_t color);
};

// ---------------------------------------------------------------------------
// App — abstract base class
// ---------------------------------------------------------------------------
class App {
public:
    virtual ~App() = default;

    // Called once when the app is first registered with AppManager
    virtual void onCreate() {}

    // Called every time the app becomes the foreground (active) app
    virtual void onEnter() {}

    // Called every loop frame; deltaMs = milliseconds since last call
    virtual void update(uint32_t deltaMs) {}

    // Called every render frame; draw to tft here
    virtual void render(TFT_eSPI& tft) {}

    // Called with each input event while this app is in the foreground
    virtual void handleInput(AppEvent event) {}

    // Called when the app is about to leave the foreground
    virtual void onExit() {}

    // Metadata — subclasses must override and return a static AppInfo
    virtual const AppInfo& getInfo() const = 0;

    // -----------------------------------------------------------------------
    // Navigation flags — set by apps to request system-level navigation.
    // AppManager checks these after each update() call.
    // -----------------------------------------------------------------------
    bool requestExit  = false;  // Pop this app off the stack
    bool requestHome  = false;  // Return to launcher immediately

    // Set to true if this app needs the full 128×128 screen (hides status bar)
    bool needsFullscreen = false;
};
